### PR TITLE
Added favicon notifications

### LINKED ISSUE #15: Add unread notifications to tray icon
It would be nice to see unread message notifications in the tray icon. We can leverage a favicon library like http://lab.ejci.net/favico.js/ to perform the badge overlay.

Unread notification message

### PR DESCRIPTION
**Pull request by twolfson**
**Depends on #23, please focus on HEAD commit**

https://github.com/twolfson/slack-for-linux/commit/90c581e70d77f9440dd19b61b6ce97a9fc5fab9b

This PR adds the long awaited tray notification support in #15.

Unread notification message

In this PR:

- Added notification support, fixes #15 
- Added bower/node module dependencies in `app/`

**Notes:**

Currently, we are saving the tray icon to the home directory under `~/.slack-for-linux-tray.png`. This was to allow multiple users to run Slack without conflict. The ideal scenario would be to save to `/tmp/` with random filenames but I was concerned about not cleaning up dead files.

/cc @wlaurance

### CODE REVIEW

**Comment by wlaurance** [comment]
I did a bad thing and went ahead and force pushed to master.

Can you reopen when it's ready again?

**Comment by twolfson** [comment]
Ah, that would do it. You will have to land one of #24 or #27 first though. Creating and reviewing the joint PR would be a nightmare to handle x_x

**Comment by twolfson** [comment]
I am going to update `master` to include this PR as landed since the `git` history is inline with that:

https://github.com/wlaurance/slack-for-linux/commits/df3284dfec2b7f14323652dccb02080a86d11c7f

https://github.com/wlaurance/slack-for-linux/commits/0e3f533c6a426b2f8bf51f2f40fe65fa55be2bc0

I will reopen #27 once the merge conflicts are resolved.

**Comment by twolfson** [comment]
Okay, I have restored #24 to being landed on `master`. It was more tedious than I thought. I couldn't seem to be able to reference the commit from the `git` CLI so I had to create a new branch in GitHub to fetch is o_o

**Pull request merged**
