### PR TITLE
Added multi team support. Fixes #21

### LINKED ISSUE #21: Allow for multiple teams
Since slack allows you to be signed into multiple teams in multiple tabs, it should be possible to introduce a "tabbed" view similar to the OS X client. Ideally There would be a list of teams you're signed in to and a facility to switch between the active teams (CTRL-#, or a similar keybinding?).

### PR DESCRIPTION
**Pull request by twolfson**
**Depends on #23, please focus on HEAD commit**

This PR adds in a sidebar for when a user is logged into multiple teams. In this PR:

- Added CSS for sidebar
- Added sidebar logic to `index.js`
- Added `slack-window` abstraction for `iframe` handling
    - Lays groundwork for handling notifications on a per-team basis

**Notes:**

Currently, it is very naive and only runs at load time. I wanted to process when the user logs into other teams but then I was abstracting into a class and realized we should have a discussion. How do we want to handle complex sets of data and their updates (e.g. logging into multiple teams)? Do we want to roll our own thing or use a framework like React?

**Missing (should be new issues created):**

- Notifications badges on each team icon
    - Also, when #24 lands we will need to update that to handle multiple teams
- Shortcuts for each team icon
- Handling logging in/out of a team

/cc @wlaurance

### CODE REVIEW

**Comment by twolfson** [comment]
Almost forgot the most important piece, screenshot:

selection_117

**Comment by yograterol** [comment]
+1

**Comment by twolfson** [comment]
Ah, good catch. I missed those lint errors. I have pushed an updated version.

**Comment by twolfson** [comment]
I am surprised this was landed. It is definitely not immediately compatible with #24's changes and seems to have introduced diff issues inside of `master` =/

https://github.com/wlaurance/slack-for-linux/blob/0e3f533c6a426b2f8bf51f2f40fe65fa55be2bc0/app/js/index.js#L67

**Comment by andrewelkins** [comment]
Awesome!

**Comment by andrewelkins** [comment]
Although, shouldn't have #30 been merged in instead?

**Comment by twolfson** [comment]
This was merged/reverted due to conflicts with #24. #30 was the fixed version that had no conflicts.

**Pull request merged**
